TourtotoSiteBundle\Entity\Land:
    type: entity
    table: land
    uniqueConstraints:
        code:
            columns:
                - code
        naam:
            columns:
                - naam
    id:
        id:
            type: integer
            nullable: false
            unsigned: false
            comment: ''
            id: true
            generator:
                strategy: IDENTITY
    fields:
        code:
            type: string
            nullable: false
            length: 12
            fixed: false
            comment: ''
        naam:
            type: string
            nullable: false
            length: 255
            fixed: false
            comment: ''
    lifecycleCallbacks: {  }
