tourtoto:
    resource: "@TourtotoBundle/Resources/config/routing.yml"
    prefix:   /

#tourtoto_site:
#    resource: "@TourtotoSiteBundle/Resources/config/routing.yml"
#    prefix:   /

app:
    resource: "@AppBundle/Controller/"
    type:     annotation
