<?php

namespace TourtotoSiteBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * RennerRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class RennerRepository extends EntityRepository 
{
    public function selectAll($filter = NULL) {
        
        //$this->dbtype = "Renner";
        $success = true;
        $data = array();
        $errors = array();
        $header = array("id", "voornaam", "achternaam", "ploegnaam", "landnaam", "active");
        
        //var_dump($data);
        
        if(isset($filter)) {
            $dr = $this->findBy($filter);
        } else {
            $dr = $this->findAll();
        }
        
        if(count($dr) > 0 && !empty($dr)) {
            foreach($dr as $record) {
        
                $data[] = array(        
                    "id"         => $record->getId(),
                    "voornaam"   => $record->getVoornaam(),
                    "achternaam" => $record->getAchternaam(),
                    "ploeg_naam" => $record->getPloeg()->getNaam(),
                    "land_naam"  => $record->getLand()->getNaam(),
                    "active"     => $record->getActive()      
                        
                );
            }
         } 
         else 
             {
        
            $success = false;
            $errors[] = array("field" => $this->getClassName(),
                              "error" => "e_no_data_found");
        }
        
        $result = array("success" => $success, 
                        "data"    => $data, 
                        "errors"  => $errors,
                        "header"  => $header);  
        return($result);
        
    }
    
    
//    public function selectOne($id) {
//        $data = $this->selectAll(array("id"=>$id));
//        return($data);
//    }
    
//    public function saveData($params)
//    {
//        
//        $dr = new vrRecepten();
//        if ($params["id"] != null)
//        {
//             $data = $this->findBy(array("id" => $params["id"]));
//             if ($data != null)
//            {
//                 $data=array([0]);
//            }
//        }
//            
//        
//        
//        $dr->setRcptNaam($params["rcpt_naam"]);
//        $dr->setRcptKeuken($params["rcpt_keuken"]);
//        $dr->setRcptKorteBeschrijving($params["rcpt_korte_beschrijving"]);
//        
//        $this->getEntityManager()->persist($dr);
//        $this->getEntityManager()->flush();
//        
//        $id=$dr->getId();
//        $data = $this->selectAll(array("id" => $id));
//        return($data);
//    }
    
    
}
